name: FSR
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  slide_to_act: any
  url_launcher: ^6.2.6
  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/giveaway_banner.png
    - assets/giveaway_back_banner.png
    - assets/main_banner.png
    - assets/master_cloud_banner.png
    - assets/master_detail_banner.png
    - assets/master_join_banner.png
    - assets/role_selection_banner.png
    - assets/city_selection_banner.png
    - assets/center_memoji.png
    - assets/avatar1.png
    - assets/avatar2.png
    - assets/avatar3.png
    - assets/avatar4.png
    - assets/avatar5.png
    - assets/avatar6.png
    - assets/m1.png
    - assets/m2.png
    - assets/m3.png
    - assets/m4.png
    - assets/m5.png
    - assets/m6.png
    - assets/work1.png
    - assets/work2.png
    - assets/artists/
    - assets/master_detail_back_banner.png
    - assets/master_detail_logo_banner.png
    - assets/FSR.mp4
    - assets/artists/naidi/avatar.png
    - assets/artists/naidi/gallery1.jpg
    - assets/artists/naidi/gallery2.jpg
    - assets/artists/naidi/gallery3.jpg
    - assets/artists/aspergill/avatar.png
    - assets/artists/aspergill/gallery1.jpg
    - assets/artists/aspergill/gallery2.jpg
    - assets/artists/aspergill/gallery3.jpg
    - assets/artists/aspergill/gallery4.jpg
    - assets/artists/aspergill/gallery5.jpg
    - assets/artists/aspergill/gallery6.jpg
    - assets/artists/aspergill/gallery7.jpg
    - assets/artists/aspergill/gallery8.jpg
    - assets/artists/aspergill/gallery9.jpg
    - assets/artists/aspergill/gallery10.jpg

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
    - family: Lepka
      fonts:
        - asset: assets/fonts/Lepka.otf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
    - family: NauryzKeds
      fonts:
        - asset: assets/fonts/NauryzKeds.ttf